create database BankLoan;

USE BankLoan;

create table credit(
 CREDIT_PROFILE_ID INT PRIMARY KEY,
 CREDIT_SCORE INT,
 TOTAL_OPEN_ACCOUNTS INT,
 PAST_DEFAULTS INT,
 CREDIT_UTILIZATION_RATIO DECIMAL(10,2),
 CREDIT_HISTORY_YEARS INT,
 INQUIRIES_LAST_6_MONTHS INT,
 RISK_GRADE VARCHAR(100));
 
create table customer(
  CUSTOMER_ID int PRIMARY KEY, 
  CUSTOMER_NAME VARCHAR(100),
  AGE INT,
  GENDER VARCHAR(100),
  MARITAL_STATUS VARCHAR(100),
  STATE VARCHAR(100),
  EMPLOYMENT_TYPE varchar(100), 
  ANNUAL_INCOME int,
  DEPENDENTS INT,
  CUSTOMER_SEGMENT VARCHAR(100));
  
  create table loan(
  LOAN_ID int PRIMARY KEY,
  CUSTOMER_ID int,
  CREDIT_PROFILE_ID INT,
  LOAN_AMOUNT INT,
  INTEREST_RATE DECIMAL(10,4),
  EMI DECIMAL(10,2),
  DISBURSAL_DATE DATE,
  TENURE_MONTHS INT,
  DTI_RATIO DECIMAL(10,2),
  DEFAULT_FLAG INT,
  LOAN_STATUS VARCHAR(100),
  TOTAL_PAID_AMOUNT DECIMAL(10,2),
  OUTSTANDING_AMOUNT DECIMAL(10,2),
  DAYS_PAST_DUE INT,
  
  CONSTRAINT fk_loan_credit
    FOREIGN KEY (CREDIT_PROFILE_ID)
    REFERENCES credit(CREDIT_PROFILE_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
  CONSTRAINT fk_loan_customer
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES customer(CUSTOMER_ID)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);
    
use BankLoan;
select * from loan;
select count(*) from loan;

select * from customer;
select count(*) from customer;

select * from credit;
select count(*) from credit;




